"""Record validated V3.1 external feedback for a public writeup."""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[3]
LIB = ROOT / "lib"
if str(LIB) not in sys.path:
    sys.path.insert(0, str(LIB))

from mira.runtime import record_public_feedback_evidence


def main() -> int:
    parser = argparse.ArgumentParser(description="Append operator-supplied external feedback evidence.")
    parser.add_argument("--root", type=Path, default=ROOT, help="Mira workspace root.")
    parser.add_argument("--slug", help="Stable public writeup slug.")
    parser.add_argument(
        "--packet", type=Path, help="Feedback packet metadata JSON generated by v3_prepare_public_feedback_packet.py."
    )
    parser.add_argument("--feedback-source", required=True, help="Concrete external feedback source.")
    parser.add_argument("--published-url", help="Optional public URL the feedback refers to.")
    parser.add_argument("--feedback-url", help="Optional concrete URL for external feedback.")
    parser.add_argument("--notes", help="Optional operator note stored in the evidence artifact.")
    parser.add_argument("--json", action="store_true", help="Print result as JSON.")
    args = parser.parse_args()

    packet_slug = ""
    packet_url = ""
    if args.packet:
        try:
            packet = json.loads(args.packet.read_text(encoding="utf-8"))
        except (OSError, json.JSONDecodeError) as exc:
            parser.error(f"packet must be a readable feedback_packet.json file: {exc}")
        packet_slug = str(packet.get("slug") or "")
        packet_url = str(packet.get("published_url") or "")
        if args.slug and packet_slug and args.slug != packet_slug:
            parser.error("--slug does not match packet slug")
        if args.published_url and packet_url and args.published_url != packet_url:
            parser.error("--published-url does not match packet published_url")
    slug = args.slug or packet_slug
    published_url = args.published_url or packet_url
    if not slug:
        parser.error("--slug is required unless --packet supplies one")

    try:
        result = record_public_feedback_evidence(
            root=args.root,
            slug=slug,
            feedback_source=args.feedback_source,
            published_url=published_url,
            feedback_url=args.feedback_url,
            notes=args.notes,
        )
    except ValueError as exc:
        parser.error(str(exc))

    payload = {
        "record_id": result.record.id,
        "evidence_artifact": str(result.evidence_artifact),
        "eval_refs": result.record.eval_refs,
    }
    if args.json:
        print(json.dumps(payload, indent=2, sort_keys=True))
    else:
        print(f"Recorded public feedback: {result.record.id}")
        print(f"- artifact: {result.evidence_artifact}")
        for ref in result.record.eval_refs:
            print(f"- eval_ref: {ref}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
