"""Record validated V3.1 operator feedback for a briefing blind-sample item."""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[3]
LIB = ROOT / "lib"
if str(LIB) not in sys.path:
    sys.path.insert(0, str(LIB))

from mira.runtime import record_briefing_feedback


def main() -> int:
    parser = argparse.ArgumentParser(description="Append operator-supplied briefing feedback evidence.")
    parser.add_argument("--root", type=Path, default=ROOT, help="Mira workspace root.")
    parser.add_argument("--item-id", help="Weekly blind-sample briefing item id.")
    parser.add_argument(
        "--packet",
        type=Path,
        help="Briefing feedback packet metadata JSON generated by v3_prepare_briefing_feedback_packet.py.",
    )
    parser.add_argument("--button", required=True, help="Feedback button, such as useful or pursue_research.")
    parser.add_argument("--notes", help="Optional operator note stored in the evidence artifact.")
    parser.add_argument("--json", action="store_true", help="Print result as JSON.")
    args = parser.parse_args()

    packet_item_id = ""
    if args.packet:
        try:
            packet = json.loads(args.packet.read_text(encoding="utf-8"))
        except (OSError, json.JSONDecodeError) as exc:
            parser.error(f"packet must be a readable briefing_feedback_packet.json file: {exc}")
        packet_item_id = str(packet.get("item_id") or "")
        if args.item_id and packet_item_id and args.item_id != packet_item_id:
            parser.error("--item-id does not match packet item_id")
    item_id = args.item_id or packet_item_id
    if not item_id:
        parser.error("--item-id is required unless --packet supplies one")

    try:
        result = record_briefing_feedback(
            root=args.root,
            item_id=item_id,
            button=args.button,
            notes=args.notes,
        )
    except ValueError as exc:
        parser.error(str(exc))

    payload = {
        "record_id": result.record.id,
        "evidence_artifact": str(result.evidence_artifact),
        "eval_refs": result.record.eval_refs,
    }
    if args.json:
        print(json.dumps(payload, indent=2, sort_keys=True))
    else:
        print(f"Recorded briefing feedback: {result.record.id}")
        print(f"- artifact: {result.evidence_artifact}")
        for ref in result.record.eval_refs:
            print(f"- eval_ref: {ref}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
