"""Record validated V3.1 strategic public-writeup evidence."""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[3]
LIB = ROOT / "lib"
if str(LIB) not in sys.path:
    sys.path.insert(0, str(LIB))

from mira.runtime import record_public_writeup_evidence


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Append operator-supplied public writeup and external feedback evidence."
    )
    parser.add_argument("--root", type=Path, default=ROOT, help="Mira workspace root.")
    parser.add_argument("--slug", help="Stable evidence slug, for example a2a_manifest_note.")
    parser.add_argument(
        "--packet", type=Path, help="Publication packet metadata JSON generated by v3_prepare_public_writeup_packet.py."
    )
    parser.add_argument("--published-url", required=True, help="Concrete public URL for the published writeup.")
    parser.add_argument("--draft-artifact", type=Path, help="Optional local draft artifact to bind by preview hash.")
    parser.add_argument("--expected-preview-hash", help="Optional sha256 hash expected for --draft-artifact.")
    parser.add_argument("--feedback-source", help="Optional concrete external feedback source.")
    parser.add_argument("--feedback-url", help="Optional concrete URL for external feedback.")
    parser.add_argument("--notes", help="Optional operator note stored in the evidence artifact.")
    parser.add_argument("--json", action="store_true", help="Print result as JSON.")
    args = parser.parse_args()

    packet_slug = ""
    packet_draft_artifact = ""
    packet_preview_hash = ""
    if args.packet:
        try:
            packet = json.loads(args.packet.read_text(encoding="utf-8"))
        except (OSError, json.JSONDecodeError) as exc:
            parser.error(f"packet must be a readable publication_packet.json file: {exc}")
        packet_slug = str(packet.get("slug") or "")
        packet_draft_artifact = str(packet.get("draft_artifact") or "")
        packet_preview_hash = str(packet.get("preview_hash") or "")
        if args.slug and packet_slug and args.slug != packet_slug:
            parser.error("--slug does not match packet slug")
        if args.draft_artifact and packet_draft_artifact and str(args.draft_artifact) != packet_draft_artifact:
            parser.error("--draft-artifact does not match packet draft_artifact")
        if args.expected_preview_hash and packet_preview_hash and args.expected_preview_hash != packet_preview_hash:
            parser.error("--expected-preview-hash does not match packet preview_hash")
    slug = args.slug or packet_slug
    draft_artifact = args.draft_artifact or (Path(packet_draft_artifact) if packet_draft_artifact else None)
    expected_preview_hash = args.expected_preview_hash or packet_preview_hash
    if not slug:
        parser.error("--slug is required unless --packet supplies one")

    try:
        result = record_public_writeup_evidence(
            root=args.root,
            slug=slug,
            published_url=args.published_url,
            draft_artifact=draft_artifact,
            expected_preview_hash=expected_preview_hash,
            feedback_source=args.feedback_source,
            feedback_url=args.feedback_url,
            notes=args.notes,
        )
    except ValueError as exc:
        parser.error(str(exc))

    payload = {
        "record_id": result.record.id,
        "evidence_artifact": str(result.evidence_artifact),
        "preview_hash": result.preview_hash,
        "eval_refs": result.record.eval_refs,
    }
    if args.json:
        print(json.dumps(payload, indent=2, sort_keys=True))
    else:
        print(f"Recorded public evidence: {result.record.id}")
        print(f"- artifact: {result.evidence_artifact}")
        for ref in result.record.eval_refs:
            print(f"- eval_ref: {ref}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
