"""Record validated V3.1 customer-discovery feedback evidence."""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[3]
LIB = ROOT / "lib"
if str(LIB) not in sys.path:
    sys.path.insert(0, str(LIB))

from mira.runtime import record_customer_discovery_feedback


def main() -> int:
    parser = argparse.ArgumentParser(description="Append operator-supplied customer-discovery feedback evidence.")
    parser.add_argument("--root", type=Path, default=ROOT, help="Mira workspace root.")
    parser.add_argument(
        "--packet",
        type=Path,
        help="Customer-discovery packet metadata JSON generated by v3_prepare_customer_discovery_packet.py.",
    )
    parser.add_argument("--source", required=True, help="Concrete external source, reviewer id, interview id, or URL.")
    parser.add_argument("--insight", required=True, help="Short concrete summary of the external feedback.")
    parser.add_argument("--feedback-url", help="Optional concrete URL for the feedback source.")
    parser.add_argument("--notes", help="Optional operator notes.")
    parser.add_argument("--json", action="store_true", help="Print machine-readable JSON.")
    args = parser.parse_args()

    packet_topic = ""
    packet_question = ""
    if args.packet:
        try:
            packet = json.loads(args.packet.read_text(encoding="utf-8"))
        except (OSError, json.JSONDecodeError) as exc:
            parser.error(f"packet must be a readable customer_discovery_packet.json file: {exc}")
        packet_topic = str(packet.get("topic") or "")
        packet_question = str(packet.get("question") or "")

    try:
        result = record_customer_discovery_feedback(
            root=args.root,
            source=args.source,
            insight=args.insight,
            feedback_url=args.feedback_url,
            notes=args.notes,
            packet_topic=packet_topic,
            packet_question=packet_question,
        )
    except ValueError as exc:
        parser.error(str(exc))
    payload = {
        "record_id": result.record.id,
        "eval_refs": result.record.eval_refs,
        "evidence_artifact": str(result.evidence_artifact),
    }
    if args.json:
        print(json.dumps(payload, indent=2, sort_keys=True))
    else:
        print(f"Recorded customer discovery feedback: {result.eval_ref}")
        print(f"- evidence_artifact: {result.evidence_artifact}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
