"""The 20 V3.1 pipeline definitions from the architecture document."""

from __future__ import annotations

from mira.engine.pipeline import Pipeline, Step, Trigger


def _steps(names: list[str]) -> list[Step]:
    return [Step(name=name, type="deterministic") for name in names]


PIPELINE_SPECS: tuple[dict, ...] = (
    {
        "name": "article_creation",
        "memory_class": "creative",
        "trigger": ("event", "writing queue + cooldown"),
        "priority": 30,
        "skills": ["article_writing", "personal_voice"],
        "steps": [
            "preflight_substack_twitter",
            "snapshot_voice_scars_audience_outcomes",
            "select_idea",
            "research_outline",
            "outline_quality_gate",
            "draft",
            "de_ai_editorial",
            "content_hard_policy",
            "quality_eval",
            "publish_preflight",
            "publish_substack_idempotent",
            "social_promo_idempotent",
            "write_output_folder",
            "experience_record_proposal_gateway",
        ],
    },
    {
        "name": "podcast_production",
        "memory_class": "creative",
        "trigger": ("folder", "new article in output folder"),
        "priority": 40,
        "skills": ["podcast_production", "tts_routing"],
        "steps": [
            "snapshot_tts_scars_quality_traces",
            "monitor_article_output",
            "podcastability_check",
            "script",
            "script_quality",
            "language_detect_tts_route_synthesis_postprocess",
            "duration_policy",
            "publish_rss_idempotent",
            "experience_record_proposal_gateway",
        ],
    },
    {
        "name": "book_reading_notes",
        "memory_class": "creative",
        "trigger": ("event", "book added"),
        "priority": 40,
        "skills": ["reading", "comparative_analysis"],
        "steps": [
            "snapshot_reading_history",
            "process_chapters",
            "comparative_analysis",
            "compile_notes_de_ai",
            "novelty_gate",
            "epub_to_artifacts",
            "experience_record_proposal",
        ],
    },
    {
        "name": "social_reactive",
        "memory_class": "social",
        "trigger": ("schedule", "every 2h"),
        "priority": 30,
        "skills": ["social_reply", "anti_ai_voice"],
        "steps": [
            "snapshot_relationship_model",
            "collect_mentions_parallel",
            "classify_prioritize_draft",
            "draft_replies",
            "voice_soft_policy",
            "content_hard_policy",
            "post_replies_idempotent",
            "experience_record_proposal",
        ],
    },
    {
        "name": "social_proactive",
        "memory_class": "social",
        "trigger": ("schedule", "quota shortfall"),
        "priority": 40,
        "skills": ["social_posting"],
        "steps": [
            "quota_check",
            "generate_content",
            "voice_soft_policy",
            "content_hard_policy",
            "post_idempotent",
            "experience_record_no_kernel_change_default",
        ],
    },
    {
        "name": "weekly_growth_report",
        "memory_class": "social",
        "trigger": ("schedule", "Monday morning"),
        "priority": 40,
        "skills": ["growth_analysis"],
        "steps": [
            "collect_metrics_parallel",
            "trend_analysis",
            "target_check",
            "experience_record_proposal",
        ],
    },
    {
        "name": "intelligence_briefing",
        "memory_class": "epistemic",
        "trigger": ("schedule", "morning"),
        "priority": 30,
        "skills": ["briefing", "signal_detection"],
        "steps": [
            "preflight_eight_sources",
            "snapshot_interests_gaps",
            "fetch_sources_parallel",
            "dedup_trust_classification",
            "write_briefing_trust_labeled",
            "signal_quality_gate",
            "store_push",
            "experience_record_selective_proposal",
        ],
    },
    {
        "name": "research_deep_dive",
        "memory_class": "epistemic",
        "trigger": ("event", "research queue + slot"),
        "priority": 30,
        "skills": ["research", "literature_synthesis"],
        "steps": [
            "snapshot_open_questions_prior_research",
            "literature_search",
            "deep_analysis",
            "novel_insight_gate",
            "reading_notes",
            "distill_to_knowledge",
            "experience_record_proposal",
        ],
    },
    {
        "name": "daily_thought_discussion",
        "memory_class": "epistemic",
        "trigger": ("schedule", "10:00-20:00"),
        "priority": 40,
        "skills": ["discussion", "synthesis"],
        "steps": [
            "snapshot_open_questions_worldview_tensions",
            "pick_topic",
            "agent_a_opus",
            "agent_b_sonnet",
            "agent_c_deepseek_gemini",
            "convergence_gate",
            "synthesis",
            "log_threads_tab",
            "experience_record_proposal",
        ],
    },
    {
        "name": "daily_journal",
        "memory_class": "epistemic",
        "trigger": ("schedule", "21:00-23:00"),
        "priority": 30,
        "skills": ["journal", "pattern_recognition"],
        "steps": [
            "snapshot_todays_experience_records",
            "synthesize_threads_not_list",
            "threads_gate",
            "voice_soft_policy",
            "store_push",
            "experience_record_proposal",
        ],
    },
    {
        "name": "weekly_reflection",
        "memory_class": "epistemic",
        "trigger": ("schedule", "Sunday"),
        "priority": 30,
        "skills": ["reflection", "memory_consolidation"],
        "steps": [
            "load_week_journals_experience_records",
            "memory_consolidation",
            "update_interests_worldview",
            "depth_gate",
            "distribute_feedback",
            "proposal_gateway",
        ],
    },
    {
        "name": "market_monitor",
        "memory_class": "operational",
        "trigger": ("event", "Tetra report published"),
        "priority": 20,
        "skills": ["market_monitor"],
        "steps": [
            "watch_tetra",
            "number_verification_hard_policy",
            "compliance_hard_policy",
            "format_push",
            "experience_record_no_kernel_change_default",
        ],
    },
    {
        "name": "communication",
        "memory_class": "operational",
        "trigger": ("event", "message from iPhone / app thread"),
        "priority": 10,
        "skills": ["intent_inference", "response_synthesis"],
        "steps": [
            "snapshot_relationship_history",
            "privacy_hard_policy",
            "classify_route",
            "execute_agent",
            "quality_eval",
            "reply_thread",
            "experience_record_proposal",
        ],
    },
    {
        "name": "system_health",
        "memory_class": "operational",
        "trigger": ("schedule", "every 5 min"),
        "priority": 5,
        "skills": ["system_health"],
        "steps": [
            "heartbeat_processes_crash_tasks_failure_sig",
            "status_hard_policy",
            "experience_record_on_change",
        ],
    },
    {
        "name": "incident_response",
        "memory_class": "operational",
        "trigger": ("event", "system health exposed"),
        "priority": 5,
        "skills": ["root_cause_analysis", "coder"],
        "steps": [
            "snapshot_scars_failure_sigs",
            "diagnostic",
            "root_cause",
            "propose_fix",
            "safety_hard_policy",
            "risk_grant_required",
            "apply_fix_effect_log",
            "verify",
            "proposal_create_scar_gateway",
        ],
    },
    {
        "name": "health_wellness",
        "memory_class": "bodily",
        "trigger": ("schedule", "morning"),
        "priority": 30,
        "skills": ["health"],
        "steps": [
            "snapshot_local_only",
            "ingest_oura",
            "threshold_hard_policy",
            "trend_analysis_local_omlx",
            "alert_push",
            "experience_record_local_selective_proposal",
        ],
    },
    {
        "name": "self_evolution",
        "memory_class": "self_modification",
        "trigger": ("schedule", "13:00-16:00"),
        "priority": 40,
        "skills": ["self_evolution", "coder"],
        "steps": [
            "snapshot_scars_sigs_hypotheses_eval_calibration",
            "detect_mismatches",
            "cluster_by_failure_sig_min_count",
            "experiment_record",
            "hypothesis_quality",
            "risk_classify",
            "human_if_high_risk",
            "implement_on_branch",
            "tests_golden_set",
            "canary_observe_confirm_reject_rollback",
            "experience_record_proposal_gateway",
        ],
    },
    {
        "name": "skill_learning",
        "memory_class": "self_modification",
        "trigger": ("event", "novel technique in task result"),
        "priority": 50,
        "skills": ["skill_learning", "skill_security_audit"],
        "steps": [
            "detect_novel_pattern",
            "distill_skill",
            "security_audit_hard_policy",
            "register_assign",
            "experience_record_proposal",
        ],
    },
    {
        "name": "memory_maintenance",
        "memory_class": "self_modification",
        "trigger": ("schedule", "daily off-peak"),
        "priority": 50,
        "skills": ["memory_consolidation"],
        "steps": [
            "scan_age_size_frequency",
            "identify_stale_redundant",
            "compact_merge",
            "route_feedback",
            "decay_archive_postgres",
            "audit_dlq",
            "experience_record_proposal",
        ],
    },
    {
        "name": "deterministic_reference",
        "memory_class": "operational",
        "trigger": ("manual", "deterministic steps reference"),
        "priority": 50,
        "skills": [],
        "steps": [
            "system_health",
            "feed_fetching",
            "dedup_scoring",
            "quota_check",
            "language_detection",
            "hard_policies",
            "effect_log",
            "snapshot_manifest",
            "gateway_commit",
        ],
    },
)


def build_pipeline_catalog() -> dict[str, Pipeline]:
    catalog: dict[str, Pipeline] = {}
    for spec in PIPELINE_SPECS:
        trigger_type, trigger_detail = spec["trigger"]
        catalog[spec["name"]] = Pipeline(
            name=spec["name"],
            trigger=Trigger(trigger_type, trigger_detail),
            steps=_steps(spec["steps"]),
            priority=spec["priority"],
            version=1,
            max_duration_s=3600,
            checkpoint_every=1,
            memory_class=spec["memory_class"],
            involved_skills=spec["skills"],
        )
    return catalog


PIPELINE_CATALOG = build_pipeline_catalog()
