"""The 20 V3 pipeline definitions from the architecture document."""

from __future__ import annotations

from mira.engine.pipeline import Pipeline, Step, Trigger


def _steps(names: list[str]) -> list[Step]:
    return [Step(name=name, type="deterministic") for name in names]


PIPELINE_SPECS: tuple[dict, ...] = (
    {
        "name": "article_creation",
        "memory_class": "creative",
        "trigger": ("event", "writing queue + cooldown"),
        "priority": 30,
        "skills": ["article_writing", "personal_voice"],
        "steps": [
            "load_memory",
            "select_idea",
            "research_outline",
            "outline_quality_gate",
            "full_draft",
            "de_ai_editorial",
            "content_policy",
            "quality_eval",
            "publish_preflight",
            "publish_substack",
            "social_promo",
            "write_output",
        ],
    },
    {
        "name": "podcast_production",
        "memory_class": "creative",
        "trigger": ("folder", "new article in output folder"),
        "priority": 40,
        "skills": ["podcast_production", "tts_routing"],
        "steps": [
            "load_memory",
            "monitor_article_output",
            "podcastability_check",
            "script",
            "script_quality",
            "language_detect",
            "tts_synthesis",
            "audio_post_process",
            "duration_policy",
            "publish_rss",
        ],
    },
    {
        "name": "book_reading_notes",
        "memory_class": "creative",
        "trigger": ("event", "book added"),
        "priority": 40,
        "skills": ["reading", "comparative_analysis"],
        "steps": ["load_memory", "process_chapters", "comparative_analysis", "compile_notes", "novelty_gate", "epub"],
    },
    {
        "name": "social_reactive",
        "memory_class": "social",
        "trigger": ("schedule", "every 2h"),
        "priority": 30,
        "skills": ["social_reply", "anti_ai_voice"],
        "steps": [
            "load_memory",
            "collect_mentions",
            "classify_prioritize",
            "draft_replies",
            "anti_ai_voice",
            "post_replies",
        ],
    },
    {
        "name": "social_proactive",
        "memory_class": "social",
        "trigger": ("schedule", "quota shortfall"),
        "priority": 40,
        "skills": ["social_posting"],
        "steps": ["load_memory", "quota_check", "generate_content", "voice_and_content_policy", "post"],
    },
    {
        "name": "weekly_growth_report",
        "memory_class": "social",
        "trigger": ("schedule", "Monday morning"),
        "priority": 40,
        "skills": ["growth_analysis"],
        "steps": ["load_memory", "collect_metrics", "trend_analysis", "target_check", "strategy_adjustment"],
    },
    {
        "name": "intelligence_briefing",
        "memory_class": "epistemic",
        "trigger": ("schedule", "morning"),
        "priority": 30,
        "skills": ["briefing", "signal_detection"],
        "steps": ["load_memory", "fetch_sources", "dedup_score", "write_briefing", "signal_quality", "store_push"],
    },
    {
        "name": "research_deep_dive",
        "memory_class": "epistemic",
        "trigger": ("event", "research queue + slot"),
        "priority": 30,
        "skills": ["research", "literature_synthesis"],
        "steps": [
            "load_memory",
            "select_question",
            "literature_search",
            "deep_analysis",
            "depth_gate",
            "reading_notes",
            "distill",
        ],
    },
    {
        "name": "daily_thought_discussion",
        "memory_class": "epistemic",
        "trigger": ("schedule", "10:00-20:00"),
        "priority": 40,
        "skills": ["discussion", "synthesis"],
        "steps": [
            "load_memory",
            "pick_topic",
            "agent_a_open",
            "agent_b_critique",
            "agent_c_challenge",
            "convergence",
            "synthesis",
            "log_thread",
        ],
    },
    {
        "name": "daily_journal",
        "memory_class": "epistemic",
        "trigger": ("schedule", "21:00-23:00"),
        "priority": 30,
        "skills": ["journal", "pattern_recognition"],
        "steps": ["load_memory", "collect_day", "synthesize_threads", "threads_gate", "voice_check", "store_push"],
    },
    {
        "name": "weekly_reflection",
        "memory_class": "epistemic",
        "trigger": ("schedule", "Sunday"),
        "priority": 30,
        "skills": ["reflection", "memory_consolidation"],
        "steps": [
            "load_memory",
            "memory_consolidation",
            "update_interests_worldview",
            "depth_gate",
            "distribute_feedback",
        ],
    },
    {
        "name": "market_monitor",
        "memory_class": "operational",
        "trigger": ("event", "Tetra report published"),
        "priority": 20,
        "skills": ["market_monitor"],
        "steps": ["watch_tetra", "number_verification", "compliance", "format_push"],
    },
    {
        "name": "communication",
        "memory_class": "operational",
        "trigger": ("event", "message from iPhone / app thread"),
        "priority": 10,
        "skills": ["intent_inference", "response_synthesis"],
        "steps": ["load_memory", "message_intake", "privacy", "classify_route", "execute", "output_quality", "reply"],
    },
    {
        "name": "system_health",
        "memory_class": "operational",
        "trigger": ("schedule", "every 5 min"),
        "priority": 5,
        "skills": ["system_health"],
        "steps": ["heartbeat_processes_logs", "status_check", "alert_if_degraded"],
    },
    {
        "name": "incident_response",
        "memory_class": "operational",
        "trigger": ("event", "system health exposed"),
        "priority": 5,
        "skills": ["root_cause_analysis", "coder"],
        "steps": [
            "load_memory",
            "diagnostic_snapshot",
            "root_cause",
            "propose_fix",
            "safety",
            "approval",
            "apply_fix",
            "verify",
        ],
    },
    {
        "name": "health_wellness",
        "memory_class": "bodily",
        "trigger": ("schedule", "morning"),
        "priority": 30,
        "skills": ["health"],
        "steps": ["load_memory", "ingest_oura", "threshold_checks", "trend_analysis", "alert_push"],
    },
    {
        "name": "self_evolution",
        "memory_class": "self_modification",
        "trigger": ("schedule", "13:00-16:00"),
        "priority": 40,
        "skills": ["self_evolution", "coder"],
        "steps": [
            "load_memory",
            "detect_mismatches",
            "form_hypothesis",
            "hypothesis_quality",
            "safety",
            "approval",
            "implement_change",
            "test_suite",
            "deploy_gate",
        ],
    },
    {
        "name": "skill_learning",
        "memory_class": "self_modification",
        "trigger": ("event", "novel technique in task result"),
        "priority": 50,
        "skills": ["skill_learning", "skill_security_audit"],
        "steps": [
            "load_memory",
            "detect_novel_pattern",
            "distill_skill",
            "security_audit",
            "completeness",
            "register_assign",
        ],
    },
    {
        "name": "memory_maintenance",
        "memory_class": "self_modification",
        "trigger": ("schedule", "daily off-peak"),
        "priority": 50,
        "skills": ["memory_consolidation"],
        "steps": [
            "scan",
            "identify_stale_redundant",
            "compact_merge",
            "apply_decay",
            "route_feedback",
            "archive_expired",
            "audit_dlq",
        ],
    },
    {
        "name": "deterministic_reference",
        "memory_class": "operational",
        "trigger": ("manual", "deterministic steps reference"),
        "priority": 50,
        "skills": [],
        "steps": [
            "system_health",
            "feed_fetching",
            "dedup_scoring",
            "quota_check",
            "language_detection",
            "hard_policies",
        ],
    },
)


def build_pipeline_catalog() -> dict[str, Pipeline]:
    catalog: dict[str, Pipeline] = {}
    for spec in PIPELINE_SPECS:
        trigger_type, trigger_detail = spec["trigger"]
        catalog[spec["name"]] = Pipeline(
            name=spec["name"],
            trigger=Trigger(trigger_type, trigger_detail),
            steps=_steps(spec["steps"]),
            priority=spec["priority"],
            version=1,
            max_duration_s=3600,
            checkpoint_every=1,
            memory_class=spec["memory_class"],
            involved_skills=spec["skills"],
        )
    return catalog


PIPELINE_CATALOG = build_pipeline_catalog()
